---
all:
  children:
    macos:
      hosts:
        macbook:
          ansible_host: localhost
    archlinux:
      hosts:
        archbox:
          ansible_host: 10.0.0.133
          ansible_user: sn0w
      children:
        gaming:
          hosts:
            archbox:
