---
- name: Regenerate GRUB config
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true

- name: Regenerate initramfs
  ansible.builtin.command: mkinitcpio -P
  changed_when: true
